### ISSUE TITLE
No error when assign value to non-existent mandala var in terminal

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-gcs#12]
est.pos.lat=10; //ok
est.pos.latitude=10; //also ok

**Comment by uavinda** [comment]
It is due to Qt's JS behavior - you define a var by setting it's value. Although, [AppEngine](https://github.com/uavos/apx-gcs/blob/62cd9056924473fb388f0676dd478dd9a56b9e16/src/lib/ApxCore/App/AppEngine.cpp#L164) should check and validate such cases.

Confirmed.
