### ISSUE TITLE
Object.defineProperty regression in 11.0.49

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-gcs#15]
app - unknown - Object.defineProperty(apx.tools.diginavis.my_requests.flight_requests.approved.768891a7_4f36_4228_a6bc_bba1300264eb,'start_work',{enumerable:false,configurable:false,writable:false}) SyntaxError: Expected token `)'

I can't define cpp code, that cause this problem (maybe, because qml works asynchronously). But if you really need it, I will try to write minimal work example.

**Comment by uavinda** [comment]
It seems the property or object does not exist anymore. This is just a temporary warning and can be ignored by now. Will fix that in the next releases.

**Comment by uavinda** [comment]
fixed
