### ISSUE TITLE
Mission update

### ISSUE THREAD

**Issue by SlavaVasiukovich** [uavos/apx-gcs#17]
GCS crashes during mission updating.
Console message "Segmentation fault (core dumped)"

**Comment by uavinda** [comment]
Please, attach logs from ~/Documents/UAVOS/Logs

**Comment by SlavaVasiukovich** [comment]
[APX.txt](https://github.com/uavos/apx-gcs/files/6312767/APX.txt)

**Comment by uavinda** [comment]
Can you provide a system/OS log of the crash?

How to reproduce?
GCS version?
OS/version?
Steps?

**Comment by SlavaVasiukovich** [comment]
**Environment:**
OS version - Kubuntu 20.04
GCU version - APX_Ground_Control-11.0.128-linux-x86_64

**Steps to reproduce:**
1. Run GCU ( APX_Ground_Control-11.0.128-linux-x86_64.AppImage)
2. Click 'Software in the loop simulation' button
3. Click 'Launch' on opened popup
4. Right click on the map
5. Click 'Waypoint' option
6. Click 'Upload the vehicle' button

**Actual result:**
GCS crashes during mission updating. Please see attached logs - 
[syslog.txt](https://github.com/uavos/apx-gcs/files/6313971/syslog.txt)
![index](https://user-images.githubusercontent.com/76041861/114786658-2a414b00-9d87-11eb-8369-8c13bd55092d.jpeg)

**Comment by uavinda** [comment]
fixed
