### ISSUE TITLE
Missed numbers in overlay menu of video plugin 

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-gcs#20]
If video in small-size mode, numbers is missed.
If video in big-size mode, numbers works fine.
![Screenshot_20210517_175240](https://user-images.githubusercontent.com/1128528/118509784-0af85d80-b739-11eb-8a51-354a69be51c8.png)
![Screenshot_20210517_175305](https://user-images.githubusercontent.com/1128528/118509791-0c298a80-b739-11eb-9b8b-4d9f97938b9f.png)

**Comment by uavinda** [comment]
This is not a bug, made intentionally.
