### ISSUE TITLE
There are no option for add more than one uav 

### ISSUE THREAD

**Issue by sivdesh** [uavos/apx-gcs#22]
i want to add two node with the help simulator but  i am not able to do it How can i add more then one Nodes(UAV)

**Comment by uavinda** [comment]
I assume you mean "to add more than one simulated UAV"? Unfortunately, there's no way to do this as you need to run another simulator and simulated firmware with a different UID.

**Comment by sivdesh** [comment]
So How can i add more than two uav(Nodes) at a same time?
Because i want to run more than One uav at a same time

**Comment by uavinda** [comment]
The autopilot firmware is simulated by running a binary utility located in APXFW package and extracted by GCS here `~/Documents/UAVOS/Firmware/sim/`. The sim firmware utility connects to GCS TCP server for telemetry datalink and to Xplane plugin TCP server to get sensors data and send controls. The GCS recognizes vehicle by its unique UID, which is fixed for sim firmware.

Potentially, you may run **two** PCs with `Xplane`+`plugin`+`fw sim utility`, connecting to another PC with running GCS (using `-t` option). Although, the GCS will not recognize two vehicles, as both simulated firmwares have the same UID. To make this work we need to add feature to the APX firmware - to make the `sim fw utility` capable to accept command line option such as "override vehicle UID".

**Comment by sivdesh** [comment]
Is possible live video streaming in gcs ?

**Comment by uavinda** [comment]
The future APXFW release will fix this issue by mixing the vehicle UID with the callsign. I.e. to simulate more than one vehicle, follow the above procedure, but configure different callsigns for UAVs. In this case the number of UAVs simulated at the same time is not limited.

**Comment by uavinda** [comment]
> Is possible live video streaming in gcs ?

Sure, through included VideoStreaming plugin and GStreamer library.
