### ISSUE TITLE
How to override gcs host ip address i want to use my local ip address

### ISSUE THREAD

**Issue by sivdesh** [uavos/apx-gcs#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
How to override gcs host ip address

**Comment by uavinda** [comment]
>The autopilot firmware is simulated by running a binary utility located in APXFW package and extracted by GCS here `~/Documents/UAVOS/Firmware/sim/`. The sim firmware utility connects to GCS TCP server for telemetry datalink and to Xplane plugin TCP server to get sensors data and send controls. The GCS recognizes vehicle by its unique UID, which is fixed for sim firmware.

Thus, just run the binary utility found in folder `~/Documents/UAVOS/Firmware/sim/` with the key `-h` to get usage help.

F.ex.
```
./sim-darwin -t 192.168.1.56
```
