### ISSUE TITLE
Can't build GCS

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-gcs#3]
After `cmake -H. -Bbuild -G Ninja` next error occured:

```
CMake Error at cmake/apx_gcs_meta.cmake:26 (apx_metadata):
  apx_metadata Function invoked with incorrect arguments for function named:
  apx_metadata
Call Stack (most recent call first):
  CMakeLists.txt:78 (apx_metadata_generate)
```

**Comment by uavinda** [comment]
include full cmake log

**Comment by uavinda** [comment]
workaround: 
```
cmake -H. -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release
```

**Comment by smarttowel** [comment]
[full_cmake_log.txt](https://github.com/uavos/apx-gcs/files/6048643/full_cmake_log.txt)
[CMakeOutput.log](https://github.com/uavos/apx-gcs/files/6048644/CMakeOutput.log)

Workaround works fine
