### ISSUE TITLE
Fact and long string problem

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-gcs#4]
I have Fact with Enum type and several long strings. Some UI problems on the screenshot below. What about ElideRight by default?

![image](https://user-images.githubusercontent.com/1128528/109518720-914abf00-7abb-11eb-8036-391edcd6e82f.png)

**Comment by uavinda** [comment]
ComboBox `elide` option is not available in QtQuick.Controls 2. Although, I've optimized value positioning through anchors.
BTW, it is better to avoid using of such long strings in enums and values, to keep the UI clean and easy for UAV operator.

**Comment by smarttowel** [comment]
Maybe, it's can be done with https://doc.qt.io/qt-5/qtquickcontrols2-customize.html#customizing-combobox?
