### ISSUE TITLE
Crash Linux 20.04 LTS when install tool for building GCS

### ISSUE THREAD

**Issue by uavosvn** [uavos/apx-gcs#8]
Hi,
I was try to install tool follow Dockerfile for building GCS with Cmake. My computer problem after run step  # libs: appimageupdate. 
Reinstall Linux again and find libfuse-dev can cause computer black screen after reboot. 
Same problem in 2 computer Panasonic and macbook pro 14.3.
Thanks

**Comment by uavinda** [comment]
workaround: comment out [AppUpdate plugin](https://github.com/uavos/apx-gcs/blob/main/src/Plugins/System/CMakeLists.txt).

**Comment by uavosvn** [comment]
> 
> 
> workaround: comment out [AppUpdate plugin](https://github.com/uavos/apx-gcs/blob/main/src/Plugins/System/CMakeLists.txt).

Got it! I'm just install tool of cmake and QT5. Done!
