### ISSUE TITLE
GCU crashes when trying to update config. 

### ISSUE THREAD

**Issue by SlavaVasiukovich** [uavos/apx-gcs#80]
1. Run GCU and SIM on the first PC. 
2. On the second PC, run GCU and connect to the first one via TCP. 
3. In Vehicle Configuration window update a parameter (e.g sim > autopilot > roll > kp)
4. When trying to update the config via the second PC, the GCU on the first PC crashes.

This behavior is observed in version 11.1.17.
MacOS

**Comment by SlavaVasiukovich** [comment]
@uavinda I think this commit 51d6947f8620a3a583f10b1752356c5dadb5e503 solves this problem.

**Comment by uavinda** [comment]
yes
